[package]
name = "option_protocol"
version = "0.1.0"
description = "Permissionless FX vanilla put option RFQ on Solana (Kodrat)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "option_protocol"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = [
    "anchor-lang/idl-build",
    "anchor-spl/idl-build",
    "option_protocol_types/idl-build",
]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { version = "1.0.1", features = ["init-if-needed"] }
anchor-spl = { version = "1.0.1", features = ["token", "associated_token"] }
borsh = { version = "1", features = ["derive"] }
option_protocol_types = { path = "../../option_protocol_types", features = ["anchor"] }
solana-program = { version = "3", features = ["dev-context-only-utils"] }

[dev-dependencies]
anchor-lang = { version = "1.0.1", features = ["init-if-needed"] }
anchor-spl = { version = "1.0.1", features = ["token", "associated_token"] }
borsh = "1"
ed25519-dalek = "2"
litesvm = { version = "0.10.0", features = ["precompiles"] }
option_protocol_types = { path = "../../option_protocol_types" }
rand = "0.8"
solana-keypair = "3.0.1"
solana-message = "3.0.1"
solana-program = "3"
solana-pubkey = "4.0.0"
solana-signer = "3.0.0"
solana-transaction = { version = "3.0.2", features = ["bincode"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
